{{- if and .Values.env (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "symbi.fullname" . }}
  labels:
    {{- include "symbi.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
